lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/250120_unimod_tables.xml
nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: Jonas Scheid, Steffen Lemke, Leon Bichmann, Marissa Dubbelaar
  description: Identify and quantify peptides from mass spectrometry raw data
  force: false
  is_nfcore: true
  name: mhcquant
  org: nf-core
  outdir: .
  version: 2.7.0dev
