name: "openms_idmassaccuracy"
description: Computes the fragment and/or precursor mass accuracy of identified
  peptides against the original spectra.
keywords:
  - mass accuracy
  - idXML
  - mzML
  - openms
  - proteomics
tools:
  - "openms":
      description: "OpenMS is an open-source software C++ library for LC-MS data management
        and analyses"
      homepage: "https://openms.de"
      documentation: "https://openms.readthedocs.io/en/latest/index.html"
      tool_dev_url: "https://github.com/OpenMS/OpenMS"
      doi: "10.1038/s41592-024-02197-7"
      licence: ["BSD"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test' ]`
    - mzmls:
        type: file
        description: Spectra files used for identification.
        pattern: "*.{mzML}"
        ontologies: []
    - idxmls:
        type: file
        description: Peptide identification results matching the spectra.
        pattern: "*.{idXML}"
        ontologies: []
output:
  frag_err:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*frag_mass_err.tsv":
          type: file
          description: TSV with fragment mass error measurements per PSM.
          pattern: "*frag_mass_err.tsv"
          ontologies: []
  prec_err:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*prec_mass_err.tsv":
          type: file
          description: Optional TSV with precursor mass error measurements per PSM.
          pattern: "*prec_mass_err.tsv"
          ontologies: []
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - openms:
          type: string
          description: The name of the tool
      - "FileInfo --help 2>&1 | sed -nE 's/^Version: ([0-9.]+).*/\\1/p'":
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@jonasscheid"
maintainers:
  - "@jonasscheid"
